name: Build Fifi gerber files

on:
  push:
    tags:
      - 'fifi-v[0-9]+.[0-9]+*'

jobs:
  release-gerber-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Export Fifi gerber files
        uses: nerdyscout/kicad-exports@v2.2
        with:
          config: .kiplot.yml
          dir: pcb/gerber
          board: pcb/fifi_split_keeb.kicad_pcb
          schema: pcb/fifi_split_keeb.sch
      
      - name: Zip Gerber files
        run: |
          zip -r --junk-paths fifi-keeb-gerber.zip pcb/gerber
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}